### ISSUE TITLE
How can I generate 3d graph in Gibson Env

### ISSUE THREAD

**Issue by GELIELEO** [StanfordVL/3DSceneGraph#3]
If I download the raw gibson env data, how can i generate the 3d graph?

**Comment by roeiherz** [comment]
I have the same issue.

**Comment by eg4000** [comment]
Same here

**Comment by ir0** [comment]
The graph's nodes are provided with the annotations, which you can populate using the provided code. Since the graph is dense and there is a plethora of combinations to create between elements, we didn't provide relationship annotations. It should be relatively straightforward to compute queried relationships given the node annotations (e.g., relative volume between two objects or if two objects belong to the same space), but we are planning on releasing some code for that in the next weeks. Let me know if you have more questions.

**Comment by eg4000** [comment]
Hi @ir0 , thank you for the answer,

In the supplementary material, it states that one of the object attribute is:

> Color(O):  This  specifies  the  most  common  color  on  the object.

In addition, Fig. 1 in the paper and the demo video show that **color** and **shape** are both object-level attributes. However, I cannot find them anywhere in the published dataset.

Could you please help me see what I am missing?

Thanks you very much,
Eran.

**Comment by GELIELEO** [comment]
@ir0  have you release some code already?
